services:
  fastapi1:
    image: ghcr.io/p1oxer/my-fastapi-app
    container_name: fastapi_app_1
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - app_network

  fastapi2:
    image: ghcr.io/p1oxer/my-fastapi-app
    container_name: fastapi_app_2
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi1
      - fastapi2
    networks:
      - app_network

# --- Networks ---
networks:
  app_network:
    driver: bridge